name: ne_secure
description: NE Secure - Secure reporting and SOS app for your community
publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Firebase core for initialization
  firebase_core: ^2.27.0
  # Firebase authentication for OTP login
  firebase_auth: ^4.17.4
  # Cloud Firestore for storing complaints, SOS, and user profiles
  cloud_firestore: ^4.15.9
  # Geolocator for location services in SOS and complaints
  geolocator: ^11.0.0
  # Cupertino icons for iOS-style icons (optional, but recommended)
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

